{"name": "Проверка невозможности возврата заказа при некорректном трек-номере в запросе", "status": "passed", "start": 1732976692978, "stop": 1732976693057, "uuid": "58bab256-a06c-4cb7-9c79-85e3ff0b4cc0", "historyId": "05b7ea793e89588733056c6e5832cb21", "testCaseId": "05b7ea793e89588733056c6e5832cb21", "fullName": "tests.test_get_order_by_num.TestGetOrderByNum#test_get_order_by_uncorrect_num_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order_by_num"}, {"name": "subSuite", "value": "TestGetOrderByNum"}, {"name": "host", "value": "DESKTOP-4GFTOQP"}, {"name": "thread", "value": "10124-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order_by_num"}]}