{"name": "Проверка невозможности возврата заказа при некорректном трек-номере в запросе", "status": "passed", "steps": [{"name": "Получаем ID заказа по трек-номеру с произвольными данными", "status": "passed", "parameters": [{"name": "track_num", "value": "0"}], "start": 1733069179448, "stop": 1733069179538}], "start": 1733069179448, "stop": 1733069179539, "uuid": "e497e9e1-31de-4d4e-97ca-c080f9a5f851", "historyId": "05b7ea793e89588733056c6e5832cb21", "testCaseId": "05b7ea793e89588733056c6e5832cb21", "fullName": "tests.test_get_order_by_num.TestGetOrderByNum#test_get_order_by_uncorrect_num_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order_by_num"}, {"name": "subSuite", "value": "TestGetOrderByNum"}, {"name": "host", "value": "DESKTOP-4GFTOQP"}, {"name": "thread", "value": "8820-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order_by_num"}]}