{"name": "Проверка невозможности возврата заказа при некорректном трек-номере в запросе", "status": "passed", "steps": [{"name": "Получаем ID заказа по трек-номеру с произвольными данными", "status": "passed", "parameters": [{"name": "track_num", "value": "0"}], "start": 1733062133226, "stop": 1733062133358}], "start": 1733062133225, "stop": 1733062133359, "uuid": "67688f58-bf18-4aa7-8e08-954766e6534b", "historyId": "05b7ea793e89588733056c6e5832cb21", "testCaseId": "05b7ea793e89588733056c6e5832cb21", "fullName": "tests.test_get_order_by_num.TestGetOrderByNum#test_get_order_by_uncorrect_num_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order_by_num"}, {"name": "subSuite", "value": "TestGetOrderByNum"}, {"name": "host", "value": "DESKTOP-4GFTOQP"}, {"name": "thread", "value": "14896-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order_by_num"}]}